# Generated by Django 5.0.4 on 2024-05-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
