# Generated by Django 5.0.4 on 2024-05-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_id_useraccount_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="uuid",
            new_name="id",
        ),
    ]
